#!/usr/bin/env bash
# secure transfers file

display_usage() {
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}
if [  $# -le 3 ]
    then
    display_usage
    exit 1
else
scp -i '$4' -o StrictHostKeyChecking=no $1 $3@$2:/~
fi
