#!/usr/bin/env bash
# Downloads, configs and starts a server with a page that says Holberton School

sudo apt update
sudo apt -y install nginx
cd /var/www/html/
sudo chmod 777 index.nginx-debian.html
sudo echo "Holberton School" > index.nginx-debian.html
cd /etc/nginx/sites-enabled
new_string="35.237.36.104/redirect_me;\nreturn 301 google.com;\n"
sed -i "s/server_name _;/$new_string/" default
sudo service nginx restart
