#!/usr/bin/env bash
# Downloads, configs and starts a server with a page that says Holberton School

sudo apt update
sudo apt -y install nginx
cd /var/www/html/
sudo chmod 777 index.nginx-debian.html
sudo echo "Holberton School" > index.nginx-debian.html
cd /etc/nginx/sites-available
N="server_name 35.237.36.104\n return 301 $scheme://newdomain.com$request_uri;"
sudo sed -i "s/server_name _;/$N/" default
sudo service nginx restart
