#!/usr/bin/env bash
# Downloads, configs and starts a server with a page that says Holberton School

sudo apt update
sudo apt -y install nginx
cd /var/www/html/
sudo chmod 777 index.nginx-debian.html
sudo echo "Holberton School" > index.nginx-debian.html
sed -i '42a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent 42' 
cd /etc/nginx/sites-available

sudo service nginx restart
