#!/usr/bin/env bash
# Downloads, configs and starts a server with a page that says Holberton School

sudo apt update
sudo apt -y install nginx
cd /var/www/html/
sudo chmod 777 index.nginx-debian.html
echo "Holberton School" > index.nginx-debian.html
LINK="https://www.youtube.com/watch?v=QH2-TGUlwu4"
FILE="/etc/nginx/sites-available/default"
sed -i "42a rewrite ^/redirect_me ""${LINK}"" permanent;\n" $FILE
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i "44a error_page 404 /custom_404.html; location = /custom_404.html { root /var/www/html/;internal;}" $FILE
sudo service nginx restart
