#!/usr/bin/env bash
# this script dumps and zips databases

# The MySQL dump must contain all your MySQL databases
mysqldump -uroot -p$"1" --all-databases > backup.sql
# The MySQL dump file has to be compressed to a tar.gz archive
tar -cvzf "$(date +"%d-%m-%Y").tar.gz" backup.sql
