#!/usr/bin/env bash
# Restarts a server to display the default

sudo apt -y update
sudo apt -y install nginx
# remove default file link
rm /etc/nginx/sites-enabled/default
# rebuild link to default
ln -s /etc/nginx/sites-available/default rm /etc/nginx/sites-enabled/default
sudo service nginx restart
