#!/usr/bin/env bash
# Restarts a server to display the default site
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service ngninx restart
mv var/run/nginx.pid var/run/notrunning.pid
